name: CI
env:
  CARGO_TERM_COLOR: always
on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: |
          cd rust
          cargo build --release
      - name: Test
        run: |
          cd rust
          cargo test 

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: |
          cd rust
          cargo build --release

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: rust/target/release/aur-dependency-tracker
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} 