name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Build
        run: |
          cd aur-dependency-tracker/rust
          cargo build --release
      - name: Test
        run: |
          cd aur-dependency-tracker/rust
          cargo test 